name: cs229-project
channels:
  - defaults
dependencies:
  - pip=25.0
  - python=3.9.21
  - setuptools=75.8.0
  - wheel=0.45.1
  - pip:
      - acres==0.3.0
      - addict==2.4.0
      - aiofiles==23.2.1
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.8.0
      - attrs==25.1.0
      - beautifulsoup4==4.13.3
      - blinker==1.9.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - ci-info==0.3.0
      - click==8.1.8
      - configargparse==1.7
      - configobj==5.0.9
      - configparser==7.2.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - dash==2.18.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - etelemetry==0.3.1
      - exceptiongroup==1.2.2
      - fastapi==0.115.8
      - fastjsonschema==2.21.1
      - ffmpy==0.5.0
      - filelock==3.17.0
      - fitz==0.0.1.dev2
      - flask==3.0.3
      - fonttools==4.56.0
      - frontend==0.0.3
      - fsspec==2025.2.0
      - gdown==5.2.0
      - gradio==4.29.0
      - gradio-client==0.16.1
      - gradio-imageslider==0.0.20
      - h11==0.14.0
      - h5py==3.13.0
      - httpcore==1.0.7
      - httplib2==0.22.0
      - httpx==0.28.1
      - huggingface-hub==0.29.1
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - isodate==0.6.1
      - itsdangerous==2.2.0
      - jinja2==3.1.5
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-core==5.7.2
      - kiwisolver==1.4.7
      - looseversion==1.3.0
      - lxml==5.3.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - mpmath==1.3.0
      - narwhals==1.27.1
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - nibabel==5.3.2
      - nipype==1.9.2
      - numpy==1.26.4
      - open3d==0.18.0
      - opencv-python==4.11.0.86
      - orjson==3.10.15
      - packaging==24.2
      - pandas==2.2.3
      - pathlib==1.0.1
      - pdf2image==1.17.0
      - pillow==10.4.0
      - platformdirs==4.3.6
      - plotly==6.0.0
      - prov==2.0.1
      - puremagic==1.28
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydot==3.0.4
      - pydub==0.25.1
      - pygments==2.19.1
      - pyparsing==3.2.1
      - pyquaternion==0.9.9
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2025.1
      - pyxnat==1.6.3
      - pyyaml==6.0.2
      - rdflib==6.3.2
      - referencing==0.36.2
      - requests==2.32.3
      - retrying==1.3.4
      - rich==13.9.4
      - rpds-py==0.23.0
      - ruff==0.9.7
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - semantic-version==2.10.0
      - shellingham==1.5.4
      - simplejson==3.20.1
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - starlette==0.45.3
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - tomlkit==0.12.0
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - traits==7.0.2
      - typer==0.15.1
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - websockets==11.0.3
      - werkzeug==3.0.6
      - zipp==3.21.0
